### general 
general:
  n_procs: 3  # number of processes to use for parallel processing, -1 for all available cores
  attr_dataset_list: ['hlr','streamcat']
  algorithm_list: ['kmedoids']  # list of algorithms to use for parameter regionalization
  #algorithm_list: ['gower','urf','kmeans', 'kmedoids', 'hdbscan', 'birch']

donor:
  buffer_km: 200
  metric_eval_period:
    col_name: 'evalPeriod'
    value: 'full'
  metric_threshold:
    cor:
      min: 0.4
    kge: 
      min: 0.2
    nse:
      min: 0.2
    bias:
      max: 60
      absolute: TRUE

attr_datasets:
  ngen:
    attr_list: 
    attr_select_file: '{base_dir}/inputs/attr_config/attr_selection_ngen.csv'
    attr_data_file: '{base_dir}/inputs/attr_datasets/ngen/attr_ngen_{domain}.parquet'
    base_attr_list: ['elevation', 'slope', 'aspect']
  hlr:
    attr_list:
    attr_select_file: '{base_dir}/inputs/attr_config/attr_selection_hlr.csv'
    attr_data_file: '{base_dir}/inputs/attr_datasets/hlr/attr_hlr_{domain}.parquet'
    base_attr_list: ['PPT', 'SAND']
  streamcat:
    attr_list:
    attr_select_file: '{base_dir}/inputs/attr_config/attr_selection_streamcat.csv'
    attr_data_file: '{base_dir}/inputs/attr_datasets/streamcat/attr_streamcat_{domain}.parquet'
    base_attr_list: ['Precip_Minus_EVT', 'Elev', 'BFI']

snow_cover:
  consider_snowness: True  # whether to perform regionalization separately for snow-covered and snow-free basins
  snow_cover_file: '{base_dir}/inputs/snow_frac/vpu{vpu_list}_snow_frac.parquet'  # path to the snow cover data file
  column: 'snow_pc_hydroatlas'  # column name for snow cover percent in the snow cover data file
  threshold: 20 # threshold for snow cover percent to determine snowiness category

output:
    pairs:
      save: True
      path: '{base_dir}/outputs/{run_name}/pairs'
      stem: 'pairs_{algorithm_list}_{domain}_vpu{vpu_list}'
      stem_suffix: '_mswm'  # suffix for the pairs file to be used by MSWM
      format: 'parquet'
      plots:
        spatial_map: True
        histogram: True
        columns_to_plot: ['distSpatial', 'distAttr']  # columns to plot    
    params:
      save: True
      path: '{base_dir}/outputs/{run_name}/params'
      stem: 'formulation_params_{algorithm_list}_{domain}_vpu{vpu_list}'
      format: 'csv'
    attr_data_final:
      save: True
      path: '{base_dir}/outputs/{run_name}/attr_data_final'
      stem: 'attr_{domain}_vpu{vpu_list}'
      format: 'parquet'
      plots:
        spatial_map: True
        histogram: True
        columns_to_plot: ['streamcat_Elev', 'streamcat_BFI', 'streamcat_Precip_Minus_EVT','hlr_PMPE', 'hlr_SAND','hlr_TAVE']  # attributes to plot
    config_final:
      save: True
      path: '{base_dir}/outputs/{run_name}/config_parreg_final.yaml'
      format: 
    spatial_distance:
      save: True
      path: '{base_dir}/outputs/{run_name}/spatial_distance'
      format: 'parquet'

### algorithm parameters
algorithms:
  ## general parameters common to all algorithms 
  algo_general:
    # snow fraction threshold to determine snowiness category 
    min_snow_frac: 0.2
    # maximum spatial distance (km) (donors with distance larger than this value are discarded, unless no donor smaller than this threshold is available)
    max_spa_dist: 1500
    # maximum differences in some key attributes between donors and receivers as additional constraints
    max_attr_diff:
      elev_mean: 1200 
      snow_frac: 0.3 
      forest_frac: 0.5 
      urban_frac: 0.5 
      cropland_frac: 0.5 
    # maximum number of donors to keep that satisfy the attribute distance requirement
    n_donor_max: 3
    # minimum fraction of total variance explained by PCA components
    min_var_pca: 0.8
    
  ## parameters specific to gower 
  gower:
    # minimum attr distance (if one or more donors with distance smaller than this threshold, stop searching)
    min_attr_dist: 0.1
    # maximum attr distance (donors with distance larger than this value are discarded, unless no donor smaller than this threshold is available)
    max_attr_dist: 0.25
    # starting distance (neighbourhood) for searching donors (km)
    min_spa_dist: 200
    # maximum number of donors to keep that satisfy the attribute distance requirement
    n_donor_max: 3
    # distance (in km) threshold where receiver adopts a donor directly (i.e., donor/receiver overlapping each other)
    zero_spa_dist: 1
  urf: #unsupervised random forest
    # whether to perform PCA prior to applying urf (preliminary testing indicates limited difference in results)
    pca: FALSE
    # number of trees in the forest
    n_trees: 500
    # the maximum depth of each tree
    max_depth: 3
    # minimum attr distance (if one or more donors with distance smaller than this threshold, stop searching)
    min_attr_dist: 0.1
    # maximum attr distance (donors with distance larger than this value are discarded, unless no donor smaller than this threshold is available)
    max_attr_dist: 0.25
    # starting distance (neighbourhood) for searching donors (km)
    min_spa_dist: 200
    # maximum number of donors to keep that satisfy the attribute distance requirement
    n_donor_max: 3
    # distance (in km) threshold where receiver adopts a donor directly (i.e., donor/receiver overlapping each other)
    zero_spa_dist: 1    
  ## parameters specific to the K-means approach
  kmeans:
    # number of donor basins in a cluster when no further clustering is needed
    n_donor_max: 3
    # number of maximum iterations
    n_iter_max: 100
    # initialization method, choose from 'k-means++', 'random'
    init: k-means++
    # number of times the k-means algorithm is run with different centroid seeds.
    n_init: 3
  ## parameters specific to the K-mediods approach
  kmedoids:
    # number of donor basins in a cluster when no further clustering is needed
    n_donor_max: 3
    # maximum number of iterations
    n_iter_max: 100
    # initialization method, choose from 'random', 'heuristic', 'k-medoids++', 'build'
    init: heuristic
  hdbscan:
    # number of donor basins in a cluster when no further clustering is needed
    n_donor_max: 20
    # minimum cluster size (to avoid being considered noise)
    min_cluster_size: 3
  birch:
    # number of donor basins in a cluster when no further clustering is needed
    n_donor_max: 3
    # branching factor
    branching_factor: 50
    # min and max threshold parameters - the algorithm will iterate through threshold between these to identify a suitable threshold
    min_thresh: 1.5
    max_thresh: 4.0
    # maximum number of times to resample the data (since order of objects impacts the clustering results)   
    max_resample: 20 
    